config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :discussions, only: [:index]
  root to: "main#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
	attribute :user
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user, default: -> { Current.user }
  
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :username, presence: true, uniqueness: true

  has_many :discussions, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_current_user, if: :user_signed_in?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  def set_current_user
    Current.user = current_user
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @discussions = Discussion.all
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    #flash.now[:notice] = "Hello there!"
    #flash.now[:alert] = "Dark side error!"
  end
end

app/controllers/users/devise_controller.rb
class Users::DeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/discussions/_discussion.html.erb
<div id="<%= dom_id(discussion) %>" class="mb-2">
  <h2><%= discussion.name %></h2>
  Pinned: <%= discussion.pinned %> | Closed: <%= discussion.closed %>
</div>

app/views/discussions/index.html.erb
<div class="d-flex justify-content-between aling-items-center">
  <h1>Discussions</h1>
  <%= link_to "New Discussion", root_path, class: "btn btn-primary" %>
</div>

<div class="row mt-4">
  <div class="col">
    <div id="discussions">
      <%= render @discussions %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireForums</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
</head>

  <body>
    <%= render 'shared/navigation'%>
      <div class="container mt-4">
        <%= render 'shared/flash'%>
        <%= yield %>
      </div>
  </body>
</html>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="alert alert-info mb-4 mt-4" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning mb-4" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "Hotwire Forums", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%= link_to "Discussions", discussions_path, class: "nav-item nav-link" %>
      </ul>

      <ul class="navbar-nav mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <%= link_to Current.user.username, edit_user_registration_path, class: "nav-item nav-link"%>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete , class: "nav-item nav-link"%>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-item nav-link"%>
          <%= link_to "Login", new_user_session_path, class: "nav-item nav-link"%>
        <% end%>
      </ul>
    </div>
  </div>
</nav>